server {
    listen 80;
    server_name nanekki.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nanekki.duckdns.org;

    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    resolver 127.0.0.11 valid=30s;
    set $upstream app;

    location /api/ {
        proxy_pass http://$upstream:8000;
    }
}
